### ISSUE TITLE
Trouve pas les titres FR des films.

### ISSUE THREAD

**Issue by Ho2x** [Ripolin/potatoygg#10]
Bonjour,

j'ai bien ajouté la langue dans le fichier comme vous l'avez dit.
Cependant mon couchpotato cherche toujours d'abord les titres en EN.

Avez-vous une solution ?
Merci d'avance.

**Comment by Ho2x** [comment]
Enfaite je n'ai pas l’impression qu'il utilise le allocine.py...

**Comment by Ripolin** [comment]
Nan couchpotato utilise themoviedb principalement (https://github.com/CouchPotato/CouchPotatoServer/blob/develop/couchpotato/core/media/movie/providers/info/themoviedb.py).

Une issue #3 avait déjà été ouverte sur ce sujet pour laquelle j'avais créé une PR chez CP. Cette dernière a été acceptée et mergée sur la branche develop de CP, donc vérifie bien que tu utilise la dernière version de CP sur la branche develop et non sur la branche master.

**Comment by Ripolin** [comment]
Duplicate of #3

**Comment by Ho2x** [comment]
J'ai effectivement modifié les deux lignes comme ceci : 

-    ak = ['ZjdmNTE3NzU4NzdlMGJiNjcwMzUyMDk1MmIzYzc4NDA=', 'ZTIyNGZlNGYzZmVjNWY3YjU1NzA2NDFmN2NkM2RmM2E=',
-          'YTNkYzExMWU2NjEwNWY2Mzg3ZTk5MzkzODEzYWU0ZDU=', 'ZjZiZDY4N2ZmYTYzY2QyODJiNmZmMmM2ODc3ZjI2Njk=']
+    ak = ['ZTIyNGZlNGYzZmVjNWY3YjU1NzA2NDFmN2NkM2RmM2E=', 'ZjZiZDY4N2ZmYTYzY2QyODJiNmZmMmM2ODc3ZjI2Njk=']

Et aussi test de modifier tous les EN du fichier par FR, mais je n'ai pas l'impression que cela fonctionne mieux.

Même en supprimant le PYC.
Bref je vais encore faire quelque test.

**Comment by Ripolin** [comment]
Arrête CP, supprime le cache (DATA_DIR/cache) et redémarre CP.

Lors d'une recherche du devrais avoir des logs de ce type ou l'on voit bien les recherches pour les locales en et fr : 

07-08 13:50:39 INFO
[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/54933?api_key=xxx&append_to_response=alternative_titles&language=en, data: []
07-08 13:50:40 INFO
[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/54933?api_key=xxx&append_to_response=alternative_titles&language=fr, data: []
07-08 13:50:40 INFO
[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/365942?api_key=xxx&append_to_response=alternative_titles&language=en, data: []
07-08 13:50:41 INFO
[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/365942?api_key=xxx&append_to_response=alternative_titles&language=fr, data: []

**Comment by Ho2x** [comment]
Effectivement cela fonctionne bien, enfaîte mon problème est plus ceci;

quand je fais une recherche dans Couchpotato avec un titre de film en FR cela fonctionne.
Cependant si je mets le titre du film en EN (comme l'automation le fait par défaut) il va rechercher le titre du film EN sur Yggtorrent, ce qui est logique.

Donc mon problème est plutôt du côté d'automation qui prend les titres sur IMDB et pas de possibilité pour prend un site genre Allociné ou TheMovieDB pour la recherche auto FR.
Je ne pense pas qu'il y ait vrmt de solution à mon problème.

Merci pour votre aide ;)
