### ISSUE TITLE
Error Finding torrents

### ISSUE THREAD

**Issue by axelpichon** [Ripolin/potatoygg#14]
### Information:
Version of CouchPotato: desktop: 3.0.1

### Logs:
```
11-14 11:18:10 ERROR [                  ygg.ygg] Failed searching release from YGG: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\CouchPotato\custom_plugins\ygg\ygg.py", line 189, in _searchOnTitle
AttributeError: 'NoneType' object has no attribute 'find_all'
 
```

**Comment by Ripolin** [comment]
I update the ygg's server hostname on master. Test this new version and keep me in touch ;p

**Comment by axelpichon** [comment]
Hello Ripolin 

Thank for your job :)

I have same error with new version 

11-14 11:18:10 ERROR [                  ygg.ygg] Failed searching release from YGG: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\CouchPotato\custom_plugins\ygg\ygg.py", line 189, in _searchOnTitle
AttributeError: 'NoneType' object has no attribute 'find_all'

11-29 20:26:58 ERROR [hpotato.core.plugins.base] Failed opening url in OMDBAPI: http://www.omdbapi.com/?type=movie&i=tt2709692 Traceback (most recent call last):
HTTPError: 401 Client Error: Unauthorized for url: http://www.omdbapi.com/?type=movie&i=tt2709692
 
```
Can you help me please ?

**Comment by Ripolin** [comment]
Do you used an old ygg hostname ? It changes a lot these last days and it can produce bugs like your. On the last version of this plugin you can change the ygg's base url on the settings page, it's no more hardcoded (see #15).

So try to download and test it after restart your CP service.

**Comment by Ripolin** [comment]
The error above appears when ygg return no result.

**Comment by mbettan** [comment]
Unfortunately it does not work for me, I updated the host name still not working

**Comment by mbettan** [comment]
I am not able to run the test folder, I am not sure why, missing dep?

**Comment by Ripolin** [comment]
No new dep. Are you using the good version of python ?
Sometimes I'm using python 3 instead of python 2 😋
