### ISSUE TITLE
Amélioration (changement multiple du hostname)

### ISSUE THREAD

**Issue by typiak84** [Ripolin/potatoygg#15]
Hello.
Le hostname change très souvent ces derniers temps.
Plutôt que modifier l'adresse dans le script à chaque fois, il serait peut-être plus intéressant de créer un paramètre supplémentaire dans le liste des settings du searcher dans laquelle on pourrait taper directement l'adresse du hostname, non?
Dans un  deuxième temps (ou autre piste), je ne sais pas de quelle manière ce serait possible (peut- etre en cliquant sur le lien YggTorrent à côté de l'icone dans les settings du searcher) mais puisqu'il y a redirection automatique vers la nouvelle adresse, serait il possible de prendre le résultat de la redirection pour modifier dynamiquement le hostname dans la liste des paramètres (setting.conf) de couchpotato?
En tout cas, merci pour ton super boulot ;)

**Comment by Ripolin** [comment]
Pour l'instant j'ai rendu l'url de ygg paramétrable au travers des settings. Peux-tu tester le commit 81caca9 develop et me dire si c'est OK pour toi ?

**Comment by typiak84** [comment]
Bien, je viens de faire le test suivant:
J'ai installé les modif du commit.
j'ai raffraichi un des film qui ne correspond pas à mes critères sur ygg:
le film est bien recherché et non trouvé comme attendu mais pas de message
d'erreur.
Ensuite, j'ai supprimé un film de ma base CouchPotato puis rajouter nouveau
dans les films à rechercher. Comme attendu, il le cherche, et il le trouve.
En bref, ça  à l'air de fonctionner!
Merci.
