### ISSUE TITLE
Error finding ygg

### ISSUE THREAD

**Issue by mbettan** [Ripolin/potatoygg#16]
12-03 05:19:52 ERROR
[ ygg.ygg] Failed searching release from YGG: Traceback (most recent call last): File "/root/.couchpotato/custom_plugins/ygg/ygg.py", line 193, in _searchOnTitle for link in soup.find(class_='results').find_all( AttributeError: 'NoneType' object has no attribute 'find_all'

Hostname configured: https://ww3.yggtorrent.gg

**Comment by Ripolin** [comment]
Duplicate of #14
