### ISSUE TITLE
Mise à jour de Sécurité chez YGG

### ISSUE THREAD

**Issue by typiak84** [Ripolin/potatoygg#17]
Bonjour Ripolin

Les recherches de fichier semblent ne plus aboutir depuis peu.
Je pense que ça peut être lié à ça: https://www2.yggtorrent.gg/forum/index.php?threads/mise-%C3%A0-jour-de-s%C3%A9curit%C3%A9-30-12-2018.11706/#post-69944

Il semble qu'ils ont rajouté une page de confirmation lors de l'accès à un lien vers un fichier...

Merci pour ton taff!

**Comment by Ripolin** [comment]
Tout est OK de mon côté. YGG a renforcé la sécurité lorsque on arrive d'un domaine tiers via un lien, ce qui n'est pa notre cas ici.

Concernant ton soucis aurais tu des logs ? Le plugin est-il actif (il se désactive automatiquement lorsqu'il n'arrive pas à se connecter un certain nombre de fois à YGG) ?

**Comment by typiak84** [comment]
Le Plugin est bien activé mais lorsque je lance une recherche dont je sais
qu'il doit trouver une réponse positive, rien ne se passe.
Exemple : les vieux fourneaux
01-04 16:37:01 INFO[core.media.movie.searcher] Search for Les Vieux
Fourneaux in 720p ignoring ETA
01-04 16:37:01 INFO[hpotato.core.plugins.base] Opening url: get
https://www2.yggtorrent.gg/engine/search?category=2145&do=search&sub_category=all&name=les+vieux+fourneaux&file=&uploader=&description=,
data: []
01-04 16:37:01 INFO[core.media.movie.searcher] Search for Book Club in
1080p ignoring ETA

**Comment by typiak84** [comment]
Salut.

Je ne suis plus certain que ça vienne de ton Plugin:
Ce soir, il vient de tomber une nouvelle version de ce film correspondant à
mes critère de recherche (720p entre 1Go et 6.5Go) et cette fois il à été
snatched.
La seule différence que je vois entre ce torrent et les autres versions qui
n'était pas "choisies" par couchpotato, c'est que toutes les autres
versions sont des WebRip. Là où je n'y comprend plus rien, c'est que dans
mes critère de recherche, je n'ai aucun mot-clé dans la liste "Ignored",
donc rien qui peu exclure les WebRip.

Voici la liste des fichiers qu'il à ignoré sur YGG depuis plusieurs jours:
Les.Vieux.Fourneaux.2018.FRENCH.720p.mHD.WEBRip.H264-GOLD 16 5 jours 1.20Go
      762   327 6
Les.Vieux.Fourneaux.2018.FRENCH.WEBRip.H264-GOLD  8 5 jours 694.40Mo 416
167 2
Les.Vieux.Fourneaux.2018.FRENCH.720p.WEBRip.H264-GOLD 47 9 jours 1.84Go
    2454  865 11

Et Voici celui qu'il à choisi ce soir:
Les.Vieux.Fourneaux.2018.FRENCH.720p.BluRay.Light.x264.AC3-ACOOL 1 2 heures
1.44Go         54     51 17


Et  le log qui ne dit pas grand chose d'utile:
1-04 21:37:02 INFO
[core.media.movie.searcher] Search for Les Vieux Fourneaux in 720p ignoring
ETA
01-04 21:37:02 INFO
[hpotato.core.plugins.base] Opening url: get
https://www2.yggtorrent.gg/engine/search?category=2145&do=search&sub_category=all&name=les+vieux+fourneaux&file=&uploader=&description=,
data: []
01-04 21:37:03 INFO
[hpotato.core.plugins.base] Opening url: get
https://www2.yggtorrent.gg/torrent/filmvid%C3%A9o/film/382868-les+vieux+fourneaux+2018+french+720p+bluray+light+x264+ac3-acool,
data: []
01-04 21:37:03 INFO
[hpotato.core.plugins.base] Opening url: get
https://api.couchpota.to/validate/bGVzLnZpZXV4LmZvdXJuZWF1eC4yMDE4LmZyZW5jaC43MjBwLmJsdXJheS5saWdodC54MjY0LmFjMy1hY29vbA==/,
data: []
01-04 21:37:03 INFO
[edia._base.providers.base] Found: score(231) on YGG:
Les.Vieux.Fourneaux.2018.FRENCH.720p.BluRay.Light.x264.AC3-ACOOL
01-04 21:37:03 INFO
[hpotato.core.plugins.base] Opening url: get
https://www2.yggtorrent.gg/engine/download_torrent?id=382868, data: []
01-04 21:37:04 INFO
[tato.core.plugins.release] Snatched
"Les.Vieux.Fourneaux.2018.FRENCH.720p.BluRay.Light.x264.AC3-ACOOL": Les
Vieux Fourneaux (2018) in 720p from YGG
01-04 21:37:04 INFO
[hpotato.core.plugins.base] Opening url: post
https://api.pushbullet.com/v2/pushes, data: ['body', 'type', 'title']
01-04 21:37:04 INFO

Si tu y comprends quelquechose...

**Comment by Ripolin** [comment]
Peux tu passer les log en debug (dans les options système il me semble) ? 

Pour info CP filtre selon plusieurs critères notamment en fonction de la taille du fichier associé à la qualité (paramétrable). Par exemple si il voit un film de 100Mo indiqué pour une qualité de 1080p, il va rejeter l'entrée.

En debug il devrait voir ce que le plugin trouve et pourquoi il jette ... normalement :grin:

**Comment by typiak84** [comment]
Merci Beaucoup.

Ça m'a pas mal aidé:
J'ai pu voir que certains étaient bloqués car le score était négatif!!!
(incompréhensible car le mode de calcul du score est une vrai plaie).
Mais surtout comme je le supposais, c'est bien les "WebRip" qui posent
problème. Il semble que Couchpotato les considère comme des screener
(apparenté à un tag ['scr']) alors qu'en fait ça n'en est pas:
[core.media.movie.searcher] Wrong:
Budapest.2018.TRUEFRENCH.WEBRIP.x264.AC3-zitoune69, looking for 720p, found
['scr']
Je ne sais pas comment il fait ce rapprochement entre le tag webrip et le
tag screener ni comment le contourner mais quand j'autorise la recherche
dans les screener, il le trouve immédiatement.
Je pense qu'on dépasse allègrement le cadre de ton plugin mais je pense que
ça peut-être intéressant que tu le saches car, pour le coup, on passe à
côté de pas mal de realease...

**Comment by Ripolin** [comment]
En effet. Pour info, si tu regardes cette ligne de CP (https://github.com/CouchPotato/CouchPotatoServer/blob/12ca4c22680961346e0aa2617941bf1a7252fc67/couchpotato/core/plugins/quality/main.py#L33) tu verra que que webrip est un alias pour le type _scr_ (champ _alternative_).

**Comment by typiak84** [comment]
Salut Ripolin.
J'ai a nouveau des probleme sur YGG.
Je voudrais savoir si tu as ce genre de souci et donc savoir si ça viens de
ton plugin Couchpotato ou pas:
J'ai ce genre d'erreur:
02-24 11:08:13 ERROR[hpotato.core.plugins.base] Failed opening url in YGG:
https://www2.yggtorrent.gg/engine/search?category=2145&do=search&sub_category=all&name=a+star+is+born&file=&uploader=&description=
Traceback (most recent call last): HTTPError: 503 Server Error: Service
Temporarily Unavailable for url:
https://www2.yggtorrent.gg/engine/search?category=2145&do=search&sub_category=all&name=a+star+is+born&file=&uploader=&description=
Alors que, si je copie l'adresse dans un navigateur, j'ai bien le résultat
de la recherche.
Suite à ça, au bout de seulement quelques essais, j'ai ça:
[hpotato.core.plugins.base] Disabled calls to www2.yggtorrent.gg for 15
minutes because so many failed requests.
Il y a peu de temps, le message d'erreur initial était différent: une
erreur 403.


Tu as une idée?
