### ISSUE TITLE
.ws domain

### ISSUE THREAD

**Issue by yao89** [Ripolin/potatoygg#23]
Le site à changer de domaine, est-ce que tu maintient toujours ce plugin ?

Si non, pourrais-tu faire un micro tuto des texte à modifier pour juste changer le domaine ?

Merci

**Comment by Ripolin** [comment]
En fait la mise à jour des URLs à travers l'IHM d'admin de CP devrait fonctionner

**Comment by yao89** [comment]
Je ne sais pas ce qu'est l'IHM, mais en modifiant dans le fichier de config le domaine, ça semble fonctionner.
Donc j'imagine que simplement en modifiant dans l'interface de CP, ça doit fonctionner de la même manière.
CP à même réussi à trouver nettement plus de films qu'avant avec ce changement de domaine... je ne sais pas pourquoi.

Merci de ton aide.

**Comment by Ripolin** [comment]
Dans l'application web , le plugin doit  apparaitre dans *Settings>Searcher location*.  De la tu peux configurer les urls de YGG (login et recherche).
