### ISSUE TITLE
Lo

### ISSUE THREAD

**Issue by typiak84** [Ripolin/potatoygg#25]
Salut Ripolin.

Depuis hier, le plugin n'arrive plus à s’authentifier sur le site ygg, dans les logs j'ai la séquence suivante:

04-14 11:59:04 ERROR
[hpotato.core.plugins.base] Failed opening url in YGG: https://www2.yggtorrent.se/user/login Traceback (most recent call last): HTTPError: 403 Client Error: Forbidden for url: https://www2.yggtorrent.se/user/login
04-14 11:59:04 ERROR
[edia._base.providers.base] Failed YGG login, disabling provider. Please check the configuration. Re-enabling the provider without fixing the problem may result in an IP ban, depending on the site.
04-14 11:59:04 ERROR
[edia._base.providers.base] Failed to login YGG: Traceback (most recent call last): File "/home29/typiak84/software/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 163, in login output = self.urlopen(self.urls['login'], data = self.getLoginParams()) File "/home29/typiak84/software/CouchPotatoServer/couchpotato/core/plugins/base.py", line 227, in urlopen response.raise_for_status() File "/home29/typiak84/software/CouchPotatoServer/libs/requests/models.py", line 837, in raise_for_status raise HTTPError(http_error_msg, response=self) HTTPError: 403 Client Error: Forbidden for url: https://www2.yggtorrent.se/user/login
04-14 11:59:04 ERROR
[edia._base.providers.base] Failed to login to: YGG

Je ne sais pas si je suis le seul à être dans ce cas mais en même temps j'ai remarqué que, lorsque je vaias su ygg avec un web browser, j'ai le message suivant:

![image](https://user-images.githubusercontent.com/23642429/79226882-60d84300-7e5f-11ea-8ce2-1cc3b716f813.png)

Je me demande donc s'il n'y a pas a nouveau un filtrage sévère reposant sur le user agent...

**Comment by Ripolin** [comment]
YGG a en effet mis en oeuvre une "sécurité" anti DDOS via cookie mettant a défaut tout système automatisant les recherches (automatisation = pas de pub = pas de revenu). Je vais tacher de regarder ça mais c'est pas gagner. Qu'il est loin le temps des APIs de T411 :disappointed: ...

**Comment by typiak84** [comment]
Comme tu as raison, qu’il est loin le temps de T411: pas les mêmes gens pas les mêmes motivations...
Je suppose qu’ils font tourner les cookies périodiquement!?
Sinon, ça serait trop simple!
Merci quand même pour tout ton boulot pour nous! Et le jour où ça s’arrêtera, on en aura bien profité grâce à toi...

Envoyé de mon iPhone

**Comment by Cmoi20** [comment]
Bonjour, je n'ai pas regardé en détail mais ils ont réussis a avoir un truc fonctionnel chez jackett. au cas ou vous pourriez prendre les mêmes méthodologies.

**Comment by Ripolin** [comment]
Jackett utilise https://github.com/RyuzakiH/CloudflareSolverRe qui est lib C# afin de resoudre le challenge JS/Cookie de YGG. https://github.com/Anorov/cloudflare-scrape existe bien pour Python mais son intégration est loin d'être chose facile.

**Comment by adrienlabigne** [comment]
Salut, ça donne quoi depuis le temps ? Je remarque que j'ai toujours des erreurs à chaque search, mais je ne sais si a cause du cookie toujours ou autre.
Merci ;)

**Comment by Ripolin** [comment]
@adrienlabigne   Couchpotato est maintenant un projet mort et archivé (comme Python 2.7 d'ailleurs), en conséquence je ne peux pas y maintenir un plugin à jour. Je te conseille de migrer sur une plateforme utilisant la suite [radarr](https://github.com/Radarr/Radarr) + [jackett](https://github.com/Jackett/Jackett) + [flaresolverr](https://github.com/FlareSolverr/FlareSolverr) maintenue par la communauté LinuxServer.
