### ISSUE TITLE
Trouve pas les titres FR

### ISSUE THREAD

**Issue by Lutak95** [Ripolin/potatoygg#3]
Salut,

Merci à toi pour ce plugins.

Cela fontionne si yggtorrent propose le titre en anglais également, mais si le titre sur yggtorrent est en FR, couchpotatoes n'arrive pas à faire le lien.

As-tu également ce problème et sais-tu comment y remédier ?

Merci d'avance !

**Comment by Danelem** [comment]
Hello, 

J'ai le même problème. Je crois que c'est plutôt un problème avec CouchPotato. 

Tu peux changer la langue du film dans l'écran du film, mais ça marche pas toujours.

**Comment by Ripolin** [comment]
De ce que je debug il s'agit plutôt d'un problème de CP (l'implémentation du client REST pour themoviedb me semble louche). Il faut encore que j'investigue avant de créer une pull request chez CP.

**Comment by Ripolin** [comment]
Cf. https://github.com/CouchPotato/CouchPotatoServer/pull/7272
