### ISSUE TITLE
Problème snatched Automatiquement

### ISSUE THREAD

**Issue by Ho2x** [Ripolin/potatoygg#9]
Bonjour,

j'ai une installation propre de Couchpotato et votre plugin ygg.

J'ai cependant un souci lors de la récupération des films.
Couchpotato ne m'indique aucune erreur et ne me met rien dans mon transmission en automatique.

Si par contre je clique manuellement sur le torrent qui m’intéresse, alors là, tout  fonctionne bien.
Mais la fonction automatique ne donne rien j'ai déjà tout essayé en regardant sur les forums, mais sans résultat.

Je vois par contre que dans la liste des torrents trouvés il ne trouve pas la SIZE des fichiers torrent de ygg.
Je me dis que peut être cela viendrait de là, vu qu'il ne connait pas la taille il ne prend pas automatiquement avec les paramètres de qualité que je lui ai donnée.
J'ai donc essayé  en mettant le minima à 0 mais sans résultat.

Donc couchpotato ne prend et n'envoie aucun torrent de façon automatique.

J'utilise la dernière version du git officiel 'MASTER' de couchpotato et non celle de votre plugin.

Avez-vous une idée ?

**Comment by Ripolin** [comment]
En effet la récupération de la taille des fichiers est cassé.

Concernant ta question, en dessous de 50Mo CP ne télécharge rien automatiquement (cf. https://github.com/CouchPotato/CouchPotatoServer/blob/12ca4c22680961346e0aa2617941bf1a7252fc67/couchpotato/core/plugins/release/main.py#L378).

Merci pour la remonté du bug :thumbsup:

**Comment by Ho2x** [comment]
Super merci beaucoup.

Simple question au passage, je voudrais cacher le menu d'option settings ETC, pour que mes amis puissent ajouter des films mais sans avoir accès à toutes les configurations de couchpotato.

Savez-vous m'aider ou m'indiquer +/- le fichier qui permet de modifier le WebUi sur couchpotato ? 
Encore merci pour le boulot et votre temps !
